services:
- type: pserv
  numInstances: 2
  scaling:
    minInstances: 2
    maxInstances: 5
    targetMemoryPercent: 60 # optional if targetCPUPercent is set
    targetCPUPercent: 60 # optional if targetMemory is set
  name: mysql-2
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 11
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
